### ISSUE TITLE
moving packgist dependancies out of dev status

### ISSUE THREAD

**Issue by andrewmclagan** [monospice/laravel-redis-sentinel-drivers#1]
Are there any timelines to move monospice/spicy-identifiers

out of dev status?

BTW this package is really really really allot better then the other redis-sentinel offerings :-) very nice.

**Comment by cyrossignol** [comment]
@andrewmclagan Thanks for the kind feedback :)

I'll start work to get that dependency to a stable version this weekend. It's been on my list for a while! Expect about a week or two from now for me to close this issue. Let me know if you need to use this sooner. I can certainly refactor out that package instead.

As you probably know already, you can set `"minimum-stability": "dev"` in `composer.json` while I finish that up. But I agree--better to use non-dev packages, especially for production...

**Comment by cyrossignol** [comment]
@andrewmclagan Should be running with stable dependencies now. Next up, Laravel 5.4...

**Comment by jacovdbergh** [comment]
@cyrossignol , any time-frame for getting this 5.4 ready?
Or an indication on what's needed? I'd like to poke around, but I'm still a bit new to all of this.
As said above, this package works a lot better (for me) than the other options around.

**Comment by cyrossignol** [comment]
@jacovdbergh I've started work on 5.4...should be a week or two until a release. I'm looking into the other issues you submitted as well. 

Thanks again for the feedback!

**Comment by jacovdbergh** [comment]
Thank you, appreciate it! If you need testing please shout
