### ISSUE TITLE
phpredis can be used?

### ISSUE THREAD

**Issue by over-star** [monospice/laravel-redis-sentinel-drivers#13]
hi，i have a question, phpredis can be used?
if i dont use predis,only use phpredis extension?

**Comment by cyrossignol** [comment]
No, not yet. Currently, the package only supports Predis for the client. In the future, it will support the PhpRedis extension as well for Laravel 5.4+. I'm waiting to see if the PhpRedis project will merge [this pull request](https://github.com/phpredis/phpredis/pull/851) before starting any significant work on this feature.

**Comment by over-star** [comment]
thks

**Comment by rihards2333** [comment]
hi, phpredis package (https://github.com/phpredis/phpredis) now supports Redis Sentinel. Do you have any plans on adding phpredis support in here as well?

**Comment by cyrossignol** [comment]
Yes, I will add support for PhpRedis clients as the Sentinel API stabilizes. According to the [release notes for PhpRedis 5.2.0 RC1](https://github.com/phpredis/phpredis/releases/tag/5.2.0RC1): 

> IMPORTANT: Sentinel support is considered experimental and the API will likely change based on user feedback.

This package will not likely provide a stable release with support for the PhpRedis extension until the PhpRedis project itself releases a stable implementation of their Sentinel API, but I started working on the integration in the meantime to prepare.
