### ISSUE TITLE
I'm using Laravel 5.2, and I have the aggregate connections issue

### ISSUE THREAD

**Issue by ghost** [monospice/laravel-redis-sentinel-drivers#16]
`Predis\NotSupportedException: Cannot initialize a MULTI/EXEC transaction over aggregate connections`
I found the latest version maybe has fixed, but how about Laravel 5.2?
Because I used  version ` "monospice/laravel-redis-sentinel-drivers": "^1.0",`.
Sorry for my poor English.

**Comment by ghost** [comment]
BTW, I got this issue with using queue.

**Comment by cyrossignol** [comment]
Hi Vogan, I'm *almost* done merging the support for transactions from version 2.4.0 back to the 1.x branch (for Laravel 5.3 and below). I should have a release ready for this in a day or two.

**Comment by cyrossignol** [comment]
Support for transactions (and the queue) in Laravel 5.2 released with version 1.3.0.
