### ISSUE TITLE
lumen 54 support

### ISSUE THREAD

**Issue by paunin** [monospice/laravel-redis-sentinel-drivers#2]
Looks great but need support for latest lumen/laravel fw

**Comment by cyrossignol** [comment]
Agreed :)

5.4 significantly changed the internal Redis implementation that this package hooks into, so support for 5.4 will need to come as the package's next major version number.

**Comment by andrewmclagan** [comment]
Why not submit a PR?

**Comment by cyrossignol** [comment]
@paunin @andrewmclagan @jacovdbergh, 5.4 is now supported as version `^2.0` of this package. As such, `2.0.x` is now the default branch for this project. Support for Laravel 5.3 and below will continue on the `1.x.x` branch and releases. 

Sorry for the delay...been quite busy changing jobs. Let me know if you find any issues!
