### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by L3o-pold** [monospice/laravel-redis-sentinel-drivers#25]
Any plan to support Laravel 6 ?

**Comment by cyrossignol** [comment]
Yes! I just moved Laravel 6 support over from my testing branch. I need to finish up some stuff for a stable release--in the meantime, you can try it out by changing the package's version constraint to `2.x-dev` in _composer.json_.

**Comment by vanushwashere** [comment]
@cyrossignol any estimates for laravel 6 support ?

**Comment by cyrossignol** [comment]
@vanushwashere Yes, I'll finish Laravel 6 support this weekend.

**Comment by vanushwashere** [comment]
Cool, waiting for it :) thx man 👌

**Comment by vanushwashere** [comment]
Any updates? Do you need any help?

**Comment by cyrossignol** [comment]
Support for Laravel 6.x released in version 2.6.0. 

Sorry for the wait!
