### ISSUE TITLE
Access change for RedisManager::resolve

### ISSUE THREAD

**Issue by lorique** [monospice/laravel-redis-sentinel-drivers#5]
Hey Cy,

I just discovered that framework 5.4.20 has an access change for the Iluminate\Redis\RedisManager::resolve method. It goes from protected to public. This means I'm getting a fatal error when updating beyond 5.4.19. This is true for lumen as well.

Not really sure how you wanna handle this, but i suppose it could be in your dependencies. 

Sorry to be the bearer of bad news. Lemme know if you need more info.

-- Lorique

**Comment by cyrossignol** [comment]
@lorique, thanks for reporting this! I'll start working on it. 

Just for reference, here's the PR: https://github.com/laravel/framework/pull/18830

**Comment by cyrossignol** [comment]
@lorique, @jacovdbergh The package now supports Laravel 5.4.20 and greater with the release of version 2.1.0. Thanks for your patience! Please let me know if you encounter any issues.

**Comment by jacovdbergh** [comment]
Thank you, tested and working for me on 5.4.27.
Appreciate the work!
