### ISSUE TITLE
Lumen 5.2 implementation

### ISSUE THREAD

**Issue by aleksmark** [monospice/laravel-redis-sentinel-drivers#7]
Any chance of using this package on lumen 5.2 ? 

I registered the service provider in bootstrap/app.php
```
$app->register(Monospice\LaravelRedisSentinel\RedisSentinelServiceProvider::class);
```
and I am gettiing an error 
```
Class session does not exist
```

**Comment by cyrossignol** [comment]
@aleksmark, thanks for reporting this. I think the package can support Lumen with a few small changes. I'll see if I can remove dependence on any Laravel-only features such as sessions.

**Comment by aleksmark** [comment]
@cyrossignol  Thank you for looking into this :+1:

**Comment by aleksmark** [comment]
@cyrossignol any update?

**Comment by cyrossignol** [comment]
@aleksmark should have a solution out for Lumen this week...just need to get a Lumen testing matrix set up for Travis. Sorry for the delay!

**Comment by cyrossignol** [comment]
@aleksmark, @lorique, @paunin, the package is now compatible with Lumen with the release of 2.2.0 (Lumen 5.4+) and 1.1.0 (Lumen 5.0 to 5.3). It supports optional [environment-based configuration](https://github.com/monospice/laravel-redis-sentinel-drivers#environment-based-configuration) for projects that want to follow Lumen's config model. 

Please let me know if you find any issues. I'm also interested to know how you prefer to configure the package for Sentinel so we can improve the project if needed. Any feedback welcome!
